import { access } from 'fs/promises'
import { exec } from 'child_process'
import { promisify } from 'util'
import path from 'path'

const execAsync = promisify(exec)

// Setup Your repo cert folder here
const certFolder = './certs'
// Setup the names of certificates needed here. These are generated by mkcert command
const certFiles = [
  path.join(certFolder, 'localhost.pem'),
  path.join(certFolder, 'localhost-key.pem'),
]
// Setup npm cert command
const npmCertCommand = 'npm run setup:dev:certs'
// Setup node_modules folder path
const nodeModulesFolder = './node_modules'

// Common function to check if a path (folder or file) exists and log the result
async function pathExists(filePath, isFolder = false) {
  try {
    await access(filePath)
    console.log(`Path exists: ${filePath} (isFolder: ${isFolder})`)
    return true
  } catch (err) {
    console.log(`Path does NOT exist: ${filePath} (isFolder: ${isFolder})`, err.message, err)
    return false
  }
}

// Function to check if the certs folder exists
async function checkCertsFolderExists() {
  console.log('Checking if cert folder exists...')
  const folderExists = await pathExists(certFolder, true)
  if (!folderExists) {
    console.log('Certificate folder does not exist.')
  } else {
    console.log('Certificate folder exists.')
  }
  return folderExists
}

// Function to check if both certificate files exist
async function checkCertFilesExists() {
  console.log('Checking if individual certificate files exist...')
  const fileChecks = await Promise.all(
    certFiles.map(async (file) => {
      const exists = await pathExists(file)
      console.log(`File check for ${file}: ${exists}`)
      return exists
    }),
  )

  if (fileChecks.every((exists) => exists)) {
    console.log('Both certificate files exist.')
  } else {
    console.log('One or more certificate files are missing.')
  }

  return fileChecks.every((exists) => exists)
}

// Function to run setup commands
async function runSetup() {
  try {
    const nodeModulesExists = await pathExists(nodeModulesFolder)
    if (!nodeModulesExists) {
      console.log('Running npm install...')
      await execAsync('npm install')
    } else {
      console.log('node_modules folder already exists. Skipping npm install.')
    }

    console.log('Running npm run setup:cert...')
    await execAsync(npmCertCommand)
    console.log('Setup completed successfully.')
  } catch (err) {
    console.error('Error during setup:', err)
  }
}

// Main function to check folder and file existence
async function checkAndSetup() {
  const folderExists = await checkCertsFolderExists()

  // Only check the files if the folder exists
  if (folderExists) {
    const filesExist = await checkCertFilesExists()
    if (filesExist) {
      console.log('All certificates are in place.')
    } else {
      console.log('Certificate files are missing.')
    }
  } else {
    console.log('Certificate folder is missing.')
    await runSetup()
  }
}

// Run the check
checkAndSetup()
